language: python

install:
  - pip install tox

script:
  - tox

env:
  - TOXENV=django18-py27
  - TOXENV=django18-py33
  - TOXENV=django18-py34
  - TOXENV=django18-py35
  - TOXENV=django19-py27
  - TOXENV=django19-py34
  - TOXENV=django19-py35
